### ISSUE TITLE
Can't load images via symbolic links?

### ISSUE THREAD

**Issue by tksharpless** [facebook/facebook360_dep#13]
On Windows, image file names that are symlinks give 'Missing file' errors.  It would be good to test if this is also the case on *nix.  While there is a good chance that part of  the fault is the Boost filesystem's known difficulties with handling Windows' nasty symlink format, my reading of the project code suggests that symlinks might not even work on Linux.  For example these lines in imageUtil.cpp::verifyImagePaths() would likely reject a symlink:
`      const bool exists = filesystem::is_regular_file(p);
      CHECK(exists) << "Missing file: " << p;
`
It is actually possible to read from Windows symlinks with Boost, but this does require some platform-specific code.  If the Linux builds already use symlinks OK, I would suggest giving this issue a low priority; but if not, a high one.
  
## Steps To Reproduce

1.  copy a calibration setup where MatchCorners runs correctly
2. replace image files with symlinks to files stored elsewhere
3. run MatchCorners

 expect "Missing file" failure.

**Comment by aparrapo** [comment]
We just tried on our side on Ubuntu and it worked fine. We created separate symlinks for each input image and ran `MatchCorners` as:

```
./MatchCorners --color=/media/fb/cache/1_frame_unpacked_rendered/background/color --matches='/media/fb/cache/1_frame_unpacked_rendered/match/matches_sim.json' --rig_in='/media/fb/cache/1_frame_unpacked_rendered/rigs/manifold_8192.json'
```

where `/media/fb/cache/1_frame_unpacked_rendered/background/color` contains symlinks for each tif.

It may be a Windows-only issue.

**Comment by tksharpless** [comment]
Thanks, Albert.  It has only recently become feasible to use symlinks on Windows with anything like the freedom one has on *nix, and there are still some extra hoops one must jump through. I may be able to enable this via the Windows build process, but it's low priority. So let's close this issue.
