### ISSUE TITLE
Tutorial link is 404:

### ISSUE THREAD

**Issue by avclubvids** [facebook/facebook360_dep#9]
## Steps To Reproduce

1. click on link: https://facebook.github.io/facebook360_dep/docs/tutorial.html
2. get 404

Describe what you expected to happen:
Link should lead to documentation

**Comment by sam598** [comment]
This link works: https://facebook.github.io/facebook360_dep/docs/install

**Comment by aparrapo** [comment]
Hi @sam598, thanks for reporting the broken link. Feel free to open a pull request with the link pointing at https://facebook.github.io/facebook360_dep/docs/install so we can give you proper attribution :)

**Comment by sam598** [comment]
I did not report the broken link, avclubvids did.

**Comment by aparrapo** [comment]
Link has been updated: https://github.com/facebook/facebook360_dep/commit/8c71de20893d83df013459fb3b2607e0ec946c99
